### ISSUE TITLE
Make the guide neutral?

### ISSUE THREAD

**Issue by msmerc** [yellowblood/sell-bcash#14]
Like most people I've no idea which chain will win-out, but a guide for exchanging between the chains is very much needed.  Would it be ok to submit tips for trading the other way too for those who are interested in that?

**Comment by yellowblood** [comment]
I've got no problem with that. It shouldn't be the same guide though, it'll be way too confusing. You can clone the guide, change it, and commit it as a PR (so it will exist as another file in the repo).

**Comment by msmerc** [comment]
Well some steps are common, right? Installing BTC & BCC wallets for example. Signing up to exchanges etc.

It's mostly the terminology in the trading steps that needs to change to be buy/sell neutral plus an extra step for securing BCC long term. I don't think it would confuse anyone to be in a single guide.

**Comment by yellowblood** [comment]
See if you can make it work. I can't promise anything.
