### ISSUE TITLE
SCAM ALERT

### ISSUE THREAD

**Issue by pekatete** [yellowblood/sell-bcash#15]
If as claimed BCC has no value, then where is the value in selling it off in the infancy of the chain?
The people giving these tutorials just want to buy your Bitcoin Cash on the cheap and sell later when the price inevitably rises. Hold till, at the very least, after Nov 2017 as you have nothing to lose by holding..

**Comment by yellowblood** [comment]
BCash does have value currently. If someone wants to sell, there's a guide for it here. Holding BCash meaning you believe that the value will rise - but if you believe BCash to be another pump-and-dump AltCoin, and you're correct, you will actually lose money if you don't sell it.

To summarize, hold the coins you believe in - sell the ones you don't.

**Comment by pekatete** [comment]
This is not a religion to say hold the coins you believe in, this is a calculated scam to get unwitting users to sell their coins on the cheap while you and your ilk buy them up. This is a disgusting, abominable and criminal enterprise and you should be ashamed of yourself.

**Comment by yellowblood** [comment]
If you truly believe that, by all means, go and buy as many BCash coins as you like. You made me laugh out loud, thank you.

**Comment by pekatete** [comment]
It is YOU the authors of this tripe that are looking to buy Bitcoin Cash / BCC on the cheap, so stop the dissonance. I have no doubt you are looking to have a big old laugh after ripping off all gullible readers, after-all, that is what all scammers look to do.

**Comment by yellowblood** [comment]
I'm sorry to disappoint you, but I truly believe BCash is a pump-and-dump AltCoin. Buying it doesn't make sense to me. I'm sticking with Bitcoin, the only non-speculative cryptocurrency out there.

As other suggested, I've added a warning to make sure no one sees this guide as a recommendation to sell BCash. It's just an How-To. 

If BCash can be manipulated by a single "scammer" publishing a selling guide on Github, well.. I guess it's not a very good coin to invest in.

**Comment by pekatete** [comment]
Again, you exhibit all the traits of propagating a scam by first re-stating the religious "you believe" Bitcoin Cash to be a pump & dump while subtly referring to it as BCash to create the notion that it is illegitimate in some way to the reader. 

But then you go on to claim yours is the only guide on selling BCC and therefore can not be a scam, when you clearly are aware that there are many such guides. you are trying to create that impression in order to provide another convincing angle to your guide, which is typical of many scams.

Finally, your statement claiming not to be interested in buying Bitcoin Cash is what would be expected of a scammer trying to coerce gullible holders to sell on the cheap. Nothing about regurgitating that statement disproves your clear act and intention to rip off in suspecting holders of Bitcoin Cash.

But the clincher must be YOUR decision to close off this issue straight after it was opened. Again, typical scammer behaviour. Why hide / censor an issue?

THIS GUIDE IS LITTERED WITH ALL THE HALLMARKS OF A SCAM AND IT IS A SCAM.

**Comment by yellowblood** [comment]
I didn't try to imply that my guide is the only guide out here. Although some people followed the guide and said it helped them. 

I have no way of proving that I'm not buying BCash because, well, cryptocurrencies are kinda anonymous.

Believe what you want and good luck to you, odd sir.

**Comment by pekatete** [comment]
Typical scammers! Your scam guide gives instructions on how to obfuscate your bitcoin holdings from your Bitcoin Cash, which would provide adequate anonymity for your Bitcoin Cash transactions (for the purpose of proving your selling activity on the Bitcoin Cash chain), but you choose to hide behind anonymity.

I'd normally call it a day at this point, but you stand to gain enormously from this scam at the expense of many unsuspecting bitcoin holders for no discernibly good reason aside from selfish self enrichment.
