### ISSUE TITLE
Best exchange site?

### ISSUE THREAD

**Issue by yellowblood** [yellowblood/sell-bcash#19]
I'll go with HitBTC despite their relatively low BCC price. I think it's low because it's the best site for selling. They require nothing more than an email address to deposit BCash and withdrawal BTC. 

I sold through HitBTC and it was quick and easy. I also sold through Bittrex but can't withdrawal my Bitcoin because of a slow and tiring verification process, which required me to provide a phone number or personal details.

Thoughts?
@Mirobit

**Comment by Mirobit** [comment]
I agree that HitBTC is the easiest way to sell. But they have also a questionable reputation (e.g. Bitcoin Magazine doesn't want to recommend them)
I think the current solution is fine. We don't recommend Bitfinex over HitBTC (at least not directly). We just provide the information.

**Comment by yellowblood** [comment]
OK, I agree. Bittrex really got on my nerves but I was able to withdraw.
